// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Aside = "_Aside";
                public readonly string _AsyncIndicator = "_AsyncIndicator";
                public readonly string _DefaultLayout = "_DefaultLayout";
                public readonly string _Footer = "_Footer";
                public readonly string _LayoutBase = "_LayoutBase";
                public readonly string _MailerLayout = "_MailerLayout";
                public readonly string _MainNav = "_MainNav";
                public readonly string _MinimalLayout = "_MinimalLayout";
                public readonly string _TopLeft = "_TopLeft";
                public readonly string _TopRight = "_TopRight";
            }
            public readonly string _Aside = "~/Views/Shared/_Aside.cshtml";
            public readonly string _AsyncIndicator = "~/Views/Shared/_AsyncIndicator.cshtml";
            public readonly string _DefaultLayout = "~/Views/Shared/_DefaultLayout.cshtml";
            public readonly string _Footer = "~/Views/Shared/_Footer.cshtml";
            public readonly string _LayoutBase = "~/Views/Shared/_LayoutBase.cshtml";
            public readonly string _MailerLayout = "~/Views/Shared/_MailerLayout.cshtml";
            public readonly string _MainNav = "~/Views/Shared/_MainNav.cshtml";
            public readonly string _MinimalLayout = "~/Views/Shared/_MinimalLayout.cshtml";
            public readonly string _TopLeft = "~/Views/Shared/_TopLeft.cshtml";
            public readonly string _TopRight = "~/Views/Shared/_TopRight.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string CartItemModel = "CartItemModel";
                public readonly string ComplaintPriority = "ComplaintPriority";
                public readonly string ComplaintStatus = "ComplaintStatus";
                public readonly string Currency = "Currency";
                public readonly string Currency_Simple = "Currency.Simple";
                public readonly string CustomerGender = "CustomerGender";
                public readonly string DateTime = "DateTime";
                public readonly string MultiSelectList = "MultiSelectList";
                public readonly string OrderComplaintModel = "OrderComplaintModel";
                public readonly string OrderModel = "OrderModel";
                public readonly string OrderModel_Summary = "OrderModel.Summary";
                public readonly string OrderStatus = "OrderStatus";
                public readonly string ProductModel = "ProductModel";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string Boolean = "Boolean";
                public readonly string CheckOutType = "CheckOutType";
                public readonly string ComplaintPriority = "ComplaintPriority";
                public readonly string ComplaintStatus = "ComplaintStatus";
                public readonly string CustomerGender = "CustomerGender";
                public readonly string MultiSelectList = "MultiSelectList";
                public readonly string OrderComplaintModel = "OrderComplaintModel";
                public readonly string OrderStatus = "OrderStatus";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
