// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static WebPlex.Applications.CompactStore.Controllers.AccountController Account = new WebPlex.Applications.CompactStore.Controllers.T4MVC_AccountController();
    public static WebPlex.Applications.CompactStore.Controllers.CartController Cart = new WebPlex.Applications.CompactStore.Controllers.T4MVC_CartController();
    public static WebPlex.Applications.CompactStore.Controllers.HomeController Home = new WebPlex.Applications.CompactStore.Controllers.T4MVC_HomeController();
    public static WebPlex.Applications.CompactStore.Controllers.OptimizationController Optimization = new WebPlex.Applications.CompactStore.Controllers.T4MVC_OptimizationController();
    public static WebPlex.Applications.CompactStore.Controllers.OrderController Order = new WebPlex.Applications.CompactStore.Controllers.T4MVC_OrderController();
    public static WebPlex.Applications.CompactStore.Controllers.ProductController Product = new WebPlex.Applications.CompactStore.Controllers.T4MVC_ProductController();
    public static T4MVC.NotificationController Notification = new T4MVC.NotificationController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Assets {
        private const string URLPATH = "~/Assets";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Fonts {
            private const string URLPATH = "~/Assets/Fonts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string Nazanin_eot = Url("Nazanin.eot");
            public static readonly string Nazanin_ttf = Url("Nazanin.ttf");
            public static readonly string Nazanin_woff = Url("Nazanin.woff");
            public static readonly string NazaninBold_eot = Url("NazaninBold.eot");
            public static readonly string NazaninBold_ttf = Url("NazaninBold.ttf");
            public static readonly string NazaninBold_woff = Url("NazaninBold.woff");
            public static readonly string Yekan_eot = Url("Yekan.eot");
            public static readonly string Yekan_ttf = Url("Yekan.ttf");
            public static readonly string Yekan_woff = Url("Yekan.woff");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Images {
            private const string URLPATH = "~/Assets/Images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string BackgroundPattern_png = Url("BackgroundPattern.png");
            public static readonly string FavIcon_png = Url("FavIcon.png");
            public static readonly string Loader_gif = Url("Loader.gif");
            public static readonly string Sprite_png = Url("Sprite.png");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Scripts {
            private const string URLPATH = "~/Assets/Scripts";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string galleria_1_4_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/galleria-1.4.2.min.js") ? Url("galleria-1.4.2.min.js") : Url("galleria-1.4.2.js");
            public static readonly string galleria_classic_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/galleria.classic.min.js") ? Url("galleria.classic.min.js") : Url("galleria.classic.js");
            public static readonly string jquery_2_1_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-2.1.3.min.js") ? Url("jquery-2.1.3.min.js") : Url("jquery-2.1.3.js");
            public static readonly string jquery_jscrollpane_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.min.jscrollpane.min.js") ? Url("jquery.min.jscrollpane.min.js") : Url("jquery.jscrollpane.js");
            public static readonly string jquery_mousewheel_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.mousewheel.min.js") ? Url("jquery.mousewheel.min.js") : Url("jquery.mousewheel.js");
            public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
            public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
            public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
            public static readonly string store_cart_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.cart.min.js") ? Url("store.cart.min.js") : Url("store.cart.js");
            public static readonly string store_catalog_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.catalog.min.js") ? Url("store.catalog.min.js") : Url("store.catalog.js");
            public static readonly string store_core_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.core.min.js") ? Url("store.core.min.js") : Url("store.core.js");
            public static readonly string store_form_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.form.min.js") ? Url("store.form.min.js") : Url("store.form.js");
            public static readonly string store_galleria_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.galleria.min.js") ? Url("store.galleria.min.js") : Url("store.galleria.js");
            public static readonly string store_messages_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.messages.min.js") ? Url("store.messages.min.js") : Url("store.messages.js");
            public static readonly string store_scrolling_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.scrolling.min.js") ? Url("store.scrolling.min.js") : Url("store.scrolling.js");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Styles {
            private const string URLPATH = "~/Assets/Styles";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string store_animations_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.animations.min.css") ? Url("store.animations.min.css") : Url("store.animations.css");
                 
            public static readonly string store_aside_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.aside.min.css") ? Url("store.aside.min.css") : Url("store.aside.css");
                 
            public static readonly string store_async_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.async.min.css") ? Url("store.async.min.css") : Url("store.async.css");
                 
            public static readonly string store_content_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.content.min.css") ? Url("store.content.min.css") : Url("store.content.css");
                 
            public static readonly string store_fonts_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.fonts.min.css") ? Url("store.fonts.min.css") : Url("store.fonts.css");
                 
            public static readonly string store_footer_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.footer.min.css") ? Url("store.footer.min.css") : Url("store.footer.css");
                 
            public static readonly string store_galleria_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.galleria.min.css") ? Url("store.galleria.min.css") : Url("store.galleria.css");
                 
            public static readonly string store_grid_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.grid.min.css") ? Url("store.grid.min.css") : Url("store.grid.css");
                 
            public static readonly string store_menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.menu.min.css") ? Url("store.menu.min.css") : Url("store.menu.css");
                 
            public static readonly string store_misc_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.misc.min.css") ? Url("store.misc.min.css") : Url("store.misc.css");
                 
            public static readonly string store_product_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.product.min.css") ? Url("store.product.min.css") : Url("store.product.css");
                 
            public static readonly string store_scrolling_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.scrolling.min.css") ? Url("store.scrolling.min.css") : Url("store.scrolling.css");
                 
            public static readonly string store_shared_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.shared.min.css") ? Url("store.shared.min.css") : Url("store.shared.css");
                 
            public static readonly string store_top_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/store.top.min.css") ? Url("store.top.min.css") : Url("store.top.css");
                 
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Uploads {
        private const string URLPATH = "~/Uploads";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Images {
            private const string URLPATH = "~/Uploads/Images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Products {
                private const string URLPATH = "~/Uploads/Images/Products";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Empty_txt = Url("Empty.txt");
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Views {
        private const string URLPATH = "~/Views";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _ViewStart_cshtml = Url("_ViewStart.cshtml");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Account {
            private const string URLPATH = "~/Views/Account";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _ChangePassword_cshtml = Url("_ChangePassword.cshtml");
            public static readonly string _Login_cshtml = Url("_Login.cshtml");
            public static readonly string _Register_cshtml = Url("_Register.cshtml");
            public static readonly string _ResetPassword_cshtml = Url("_ResetPassword.cshtml");
            public static readonly string _ResetPasswordCallback_cshtml = Url("_ResetPasswordCallback.cshtml");
            public static readonly string _UpdateProfile_cshtml = Url("_UpdateProfile.cshtml");
            public static readonly string ChangePassword_cshtml = Url("ChangePassword.cshtml");
            public static readonly string Login_cshtml = Url("Login.cshtml");
            public static readonly string Register_cshtml = Url("Register.cshtml");
            public static readonly string ResetPassword_cshtml = Url("ResetPassword.cshtml");
            public static readonly string ResetPasswordCallback_cshtml = Url("ResetPasswordCallback.cshtml");
            public static readonly string UpdateProfile_cshtml = Url("UpdateProfile.cshtml");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Cart {
            private const string URLPATH = "~/Views/Cart";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _Form_cshtml = Url("_Form.cshtml");
            public static readonly string Form_cshtml = Url("Form.cshtml");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Home {
            private const string URLPATH = "~/Views/Home";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _Error_cshtml = Url("_Error.cshtml");
            public static readonly string Error_cshtml = Url("Error.cshtml");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Notification {
            private const string URLPATH = "~/Views/Notification";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string OrderSubmitted_cshtml = Url("OrderSubmitted.cshtml");
            public static readonly string PasswordReset_cshtml = Url("PasswordReset.cshtml");
            public static readonly string PasswordResetRequested_cshtml = Url("PasswordResetRequested.cshtml");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Order {
            private const string URLPATH = "~/Views/Order";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _CheckOut_cshtml = Url("_CheckOut.cshtml");
            public static readonly string _List_cshtml = Url("_List.cshtml");
            public static readonly string _Track_cshtml = Url("_Track.cshtml");
            public static readonly string CheckOut_cshtml = Url("CheckOut.cshtml");
            public static readonly string List_cshtml = Url("List.cshtml");
            public static readonly string Track_cshtml = Url("Track.cshtml");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Product {
            private const string URLPATH = "~/Views/Product";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _Details_cshtml = Url("_Details.cshtml");
            public static readonly string _List_cshtml = Url("_List.cshtml");
            public static readonly string Details_cshtml = Url("Details.cshtml");
            public static readonly string List_cshtml = Url("List.cshtml");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Shared {
            private const string URLPATH = "~/Views/Shared";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _Aside_cshtml = Url("_Aside.cshtml");
            public static readonly string _AsyncIndicator_cshtml = Url("_AsyncIndicator.cshtml");
            public static readonly string _DefaultLayout_cshtml = Url("_DefaultLayout.cshtml");
            public static readonly string _Footer_cshtml = Url("_Footer.cshtml");
            public static readonly string _LayoutBase_cshtml = Url("_LayoutBase.cshtml");
            public static readonly string _MailerLayout_cshtml = Url("_MailerLayout.cshtml");
            public static readonly string _MainNav_cshtml = Url("_MainNav.cshtml");
            public static readonly string _MinimalLayout_cshtml = Url("_MinimalLayout.cshtml");
            public static readonly string _TopLeft_cshtml = Url("_TopLeft.cshtml");
            public static readonly string _TopRight_cshtml = Url("_TopRight.cshtml");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class DisplayTemplates {
                private const string URLPATH = "~/Views/Shared/DisplayTemplates";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string CartItemModel_cshtml = Url("CartItemModel.cshtml");
                public static readonly string ComplaintPriority_cshtml = Url("ComplaintPriority.cshtml");
                public static readonly string ComplaintStatus_cshtml = Url("ComplaintStatus.cshtml");
                public static readonly string Currency_cshtml = Url("Currency.cshtml");
                public static readonly string Currency_Simple_cshtml = Url("Currency.Simple.cshtml");
                public static readonly string CustomerGender_cshtml = Url("CustomerGender.cshtml");
                public static readonly string DateTime_cshtml = Url("DateTime.cshtml");
                public static readonly string MultiSelectList_cshtml = Url("MultiSelectList.cshtml");
                public static readonly string OrderComplaintModel_cshtml = Url("OrderComplaintModel.cshtml");
                public static readonly string OrderModel_cshtml = Url("OrderModel.cshtml");
                public static readonly string OrderModel_Summary_cshtml = Url("OrderModel.Summary.cshtml");
                public static readonly string OrderStatus_cshtml = Url("OrderStatus.cshtml");
                public static readonly string ProductModel_cshtml = Url("ProductModel.cshtml");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class EditorTemplates {
                private const string URLPATH = "~/Views/Shared/EditorTemplates";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string Boolean_cshtml = Url("Boolean.cshtml");
                public static readonly string CheckOutType_cshtml = Url("CheckOutType.cshtml");
                public static readonly string ComplaintPriority_cshtml = Url("ComplaintPriority.cshtml");
                public static readonly string ComplaintStatus_cshtml = Url("ComplaintStatus.cshtml");
                public static readonly string CustomerGender_cshtml = Url("CustomerGender.cshtml");
                public static readonly string MultiSelectList_cshtml = Url("MultiSelectList.cshtml");
                public static readonly string OrderComplaintModel_cshtml = Url("OrderComplaintModel.cshtml");
                public static readonly string OrderStatus_cshtml = Url("OrderStatus.cshtml");
            }
        
        }
    
        public static readonly string Web_config = Url("Web.config");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Assets 
        {
            public static partial class Fonts 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Images 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Scripts 
            {
                public static class _Assets
                {
                    public const string galleria_1_4_2_js = "~/Assets/Scripts/galleria-1.4.2.js"; 
                    public const string galleria_classic_js = "~/Assets/Scripts/galleria.classic.js"; 
                    public const string jquery_2_1_3_js = "~/Assets/Scripts/jquery-2.1.3.js"; 
                    public const string jquery_jscrollpane_js = "~/Assets/Scripts/jquery.jscrollpane.js"; 
                    public const string jquery_mousewheel_js = "~/Assets/Scripts/jquery.mousewheel.js"; 
                    public const string jquery_unobtrusive_ajax_js = "~/Assets/Scripts/jquery.unobtrusive-ajax.js"; 
                    public const string jquery_validate_js = "~/Assets/Scripts/jquery.validate.js"; 
                    public const string jquery_validate_unobtrusive_js = "~/Assets/Scripts/jquery.validate.unobtrusive.js"; 
                    public const string store_cart_js = "~/Assets/Scripts/store.cart.js"; 
                    public const string store_catalog_js = "~/Assets/Scripts/store.catalog.js"; 
                    public const string store_core_js = "~/Assets/Scripts/store.core.js"; 
                    public const string store_form_js = "~/Assets/Scripts/store.form.js"; 
                    public const string store_galleria_js = "~/Assets/Scripts/store.galleria.js"; 
                    public const string store_messages_js = "~/Assets/Scripts/store.messages.js"; 
                    public const string store_scrolling_js = "~/Assets/Scripts/store.scrolling.js"; 
                }
            }
            public static partial class Styles 
            {
                public static class _Assets
                {
                    public const string store_animations_css = "~/Assets/Styles/store.animations.css";
                    public const string store_aside_css = "~/Assets/Styles/store.aside.css";
                    public const string store_async_css = "~/Assets/Styles/store.async.css";
                    public const string store_content_css = "~/Assets/Styles/store.content.css";
                    public const string store_fonts_css = "~/Assets/Styles/store.fonts.css";
                    public const string store_footer_css = "~/Assets/Styles/store.footer.css";
                    public const string store_galleria_css = "~/Assets/Styles/store.galleria.css";
                    public const string store_grid_css = "~/Assets/Styles/store.grid.css";
                    public const string store_menu_css = "~/Assets/Styles/store.menu.css";
                    public const string store_misc_css = "~/Assets/Styles/store.misc.css";
                    public const string store_product_css = "~/Assets/Styles/store.product.css";
                    public const string store_scrolling_css = "~/Assets/Styles/store.scrolling.css";
                    public const string store_shared_css = "~/Assets/Styles/store.shared.css";
                    public const string store_top_css = "~/Assets/Styles/store.top.css";
                }
            }
            public static class _Assets
            {
            }
        }
        public static partial class Uploads 
        {
            public static partial class Images 
            {
                public static partial class Products 
                {
                    public static class _Assets
                    {
                    }
                }
                public static class _Assets
                {
                }
            }
            public static class _Assets
            {
            }
        }
        public static partial class Views 
        {
            public static partial class Account 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Cart 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Home 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Notification 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Order 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Product 
            {
                public static class _Assets
                {
                }
            }
            public static partial class Shared 
            {
                public static partial class DisplayTemplates 
                {
                    public static class _Assets
                    {
                    }
                }
                public static partial class EditorTemplates 
                {
                    public static class _Assets
                    {
                    }
                }
                public static class _Assets
                {
                }
            }
            public static class _Assets
            {
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108


